### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by Green-Kite** [Paoapps/KombuTime#4]
Hi @lammertw found your App and I’ve been using it for a few batches now. I’m happy to see you’ve planned adding Widgets.

Don‘t know how complicated this is but I would love to help add German translation to the app. If you need help let me know. 

Best regards

**Comment by lammertw** [comment]
Hi @Green-Kite 
That's great to hear. 
I've just added German support in this PR: https://github.com/Paoapps/KombuTime/pull/5
I don't speak a lot of German myself so I've automatically translated it. So if you could review it to see if everything has been translated correctly that would be great! Please leave your comments in that PR.
After that I'll release a new version in the stores.

**Comment by lammertw** [comment]
@Green-Kite Thanks for your feedback on the translation. The new version with German is now live in the Apple App Store and Google Play Store.

**Comment by KindOfNerdy** [comment]
Thx I'll review it - if you need further help let me know.
